import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { compareSnapshots, createSnapshot, R2_AUTHORITY } from '../delta/delta-engine.mjs';
import { createWheelDeltaSnapshot } from '../adapters/wheel/delta-wheel-adapter.mjs';

function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gee-r3-')); fs.mkdirSync(path.join(root, 'src')); fs.writeFileSync(path.join(root, 'src', 'a.json'), '{"a":1}'); fs.writeFileSync(path.join(root, 'src', 'b.json'), '{"b":1}'); return root; }
function snapshot(root, facts = [{ id: 'fact-a', value: 1, dependencies: ['src/a.json'], provenance: { sourcePath: 'src/a.json', sourceField: 'a' } }]) { return createSnapshot({ repoRoot: root, sources: [{ path: 'src/a.json', provenance: { sourcePath: 'src/a.json' } }, { path: 'src/b.json', provenance: { sourcePath: 'src/b.json' } }], facts }); }

test('R3 identical baseline is deterministic and unchanged', () => { const root = fixture(); const a = snapshot(root); const b = snapshot(root); assert.deepEqual(a, b); const result = compareSnapshots({ previous: a, current: b }); assert.deepEqual(result.deltas.map((d) => d.kind), ['UNCHANGED', 'UNCHANGED']); assert.equal(result.invalidatedFacts.length, 0); });
test('R3 mutation changes only dependent fact and preserves provenance', () => { const root = fixture(); const before = snapshot(root); fs.writeFileSync(path.join(root, 'src', 'a.json'), '{"a":2}'); const after = snapshot(root); const result = compareSnapshots({ previous: before, current: after }); assert.equal(result.deltas.find((d) => d.path === 'src/a.json').kind, 'CHANGED'); assert.equal(result.invalidatedFacts[0].id, 'fact-a'); assert.equal(result.invalidatedFacts[0].provenance.sourcePath, 'src/a.json'); });
test('R3 added and removed sources are classified', () => { const root = fixture(); const before = snapshot(root); fs.unlinkSync(path.join(root, 'src', 'b.json')); fs.writeFileSync(path.join(root, 'src', 'c.json'), '{}'); const after = createSnapshot({ repoRoot: root, sources: [{ path: 'src/a.json' }, { path: 'src/c.json' }] }); const result = compareSnapshots({ previous: before, current: after }); assert.equal(result.deltas.find((d) => d.path === 'src/b.json').kind, 'REMOVED'); assert.equal(result.deltas.find((d) => d.path === 'src/c.json').kind, 'ADDED'); });
test('R3 fails closed for missing critical input and forged digest', () => { const root = fixture(); assert.throws(() => createSnapshot({ repoRoot: root, sources: [{ path: 'src/missing.json' }] }), /MISSING_CRITICAL_SOURCE/); assert.throws(() => createSnapshot({ repoRoot: root, sources: [{ path: 'src/a.json', sha256: '0'.repeat(64) }] }), /FORGED_PREVIOUS_DIGEST/); });
test('R3 fails closed for tampered previous or current snapshot digest', () => { const root = fixture(); const previous = snapshot(root); const tamperedPrevious = structuredClone(previous); tamperedPrevious.sources[0].sha256 = '0'.repeat(64); assert.throws(() => compareSnapshots({ previous: tamperedPrevious, current: previous }), /INVALID_PREVIOUS_SNAPSHOT_DIGEST/); const tamperedCurrent = structuredClone(previous); tamperedCurrent.facts[0].value = 2; assert.throws(() => compareSnapshots({ previous, current: tamperedCurrent }), /INVALID_CURRENT_SNAPSHOT_DIGEST/); });
test('R3 invalidates changed fact content and dependencies', () => { const root = fixture(); const previous = snapshot(root); const changedValue = snapshot(root, [{ id: 'fact-a', value: 2, dependencies: ['src/a.json'], provenance: { sourcePath: 'src/a.json', sourceField: 'a' } }]); const valueResult = compareSnapshots({ previous, current: changedValue }); assert.equal(valueResult.reusableFacts.length, 0); assert.equal(valueResult.invalidatedFacts[0].reason, 'FACT_CONTENT_CHANGED'); const changedDependency = snapshot(root, [{ id: 'fact-a', value: 1, dependencies: ['src/b.json'], provenance: { sourcePath: 'src/b.json', sourceField: 'b' } }]); const dependencyResult = compareSnapshots({ previous, current: changedDependency }); assert.equal(dependencyResult.reusableFacts.length, 0); assert.equal(dependencyResult.invalidatedFacts[0].reason, 'FACT_CONTENT_CHANGED'); });
test('R3 removed dependency invalidates the previous fact without resurrecting its value', () => { const root = fixture(); const previous = snapshot(root, [{ id: 'fact-b', value: 9, dependencies: ['src/b.json'], provenance: { sourcePath: 'src/b.json', sourceField: 'b' } }]); fs.unlinkSync(path.join(root, 'src', 'b.json')); const current = createSnapshot({ repoRoot: root, sources: [{ path: 'src/a.json' }] }); const result = compareSnapshots({ previous, current }); assert.equal(result.deltas.find((delta) => delta.path === 'src/b.json').kind, 'REMOVED'); assert.equal(result.invalidatedFacts[0].id, 'fact-b'); assert.equal(Object.hasOwn(result.invalidatedFacts[0], 'value'), false); });
test('R3 unrelated fact remains reusable when another dependency changes', () => { const root = fixture(); const facts = [{ id: 'fact-a', value: 1, dependencies: ['src/a.json'], provenance: { sourcePath: 'src/a.json' } }, { id: 'fact-b', value: 2, dependencies: ['src/b.json'], provenance: { sourcePath: 'src/b.json' } }]; const previous = snapshot(root, facts); fs.writeFileSync(path.join(root, 'src', 'a.json'), '{"a":2}'); const current = snapshot(root, facts); const result = compareSnapshots({ previous, current }); assert.deepEqual(result.reusableFacts.map((fact) => fact.id), ['fact-b']); assert.deepEqual(result.invalidatedFacts.map((fact) => fact.id), ['fact-a']); });
test('R3 generic fixture and Wheel adapter retain non-authority', () => { const root = fixture(); const context = { authorityDeclaration: R2_AUTHORITY, relevantSources: [{ path: 'src/a.json', sha256: createSnapshot({ repoRoot: root, sources: [{ path: 'src/a.json' }] }).sources[0].sha256 }], facts: [{ id: 'x', value: 1, provenance: { sourcePath: 'src/a.json' } }] }; const result = createWheelDeltaSnapshot({ repoRoot: root, context }); assert.equal(result.authorityDeclaration, R2_AUTHORITY); assert.equal(result.facts[0].provenance.sourcePath, 'src/a.json'); });
test('R3 does not claim R4 capability', () => { const root = fixture(); const text = JSON.stringify(snapshot(root)); assert.equal(text.includes('Evidence Graph'), false); assert.equal(text.includes('EVIDENCE_GRAPH'), false); });
