import { authoritativeCase } from './helpers/earningsOfficialTestHarnessL4CIV1.mjs';

authoritativeCase("I1-P001", "policy", "IngestionPolicy includes datasetSeriesIdentity literal", "");
authoritativeCase("I1-P002", "policy", "ExtractionPolicy tag priorities pinned", "");
authoritativeCase("I1-P003", "policy", "latestReferencePolicy must be FORBIDDEN", "");
authoritativeCase("I1-P004", "policy", "networkDuringComputationPolicy FORBIDDEN", "");
authoritativeCase("I1-P005", "policy", "allowedSourceAuthority SEC_EDGAR only", "");
authoritativeCase("I1-P006", "policy", "jurisdictionCode US only V1", "");
authoritativeCase("I1-P007", "policy", "currencyCode USD only V1", "");
authoritativeCase("I1-P008", "policy", "admission forms closed 8-K/8-K/A/10-Q/10-K", "");
authoritativeCase("I1-P009", "policy", "8-K requires Item 2.02 for admission", "");
authoritativeCase("I1-P010", "policy", "8-K with 2.02 admitted", "");
authoritativeCase("I1-P011", "policy", "8-K/A with 2.02 admitted as independent accession", "");
authoritativeCase("I1-P012", "policy", "10-Q admitted without 2.02", "");
authoritativeCase("I1-P013", "policy", "10-K admitted without 2.02", "");
authoritativeCase("I1-P014", "policy", "CURRENT_REPORTED_PERIODS_ONLY policy pin", "");
authoritativeCase("I1-P015", "policy", "EPS diluted-only tag policy", "");
authoritativeCase("I1-P016", "policy", "Revenue consolidated total policy", "");
authoritativeCase("I1-P017", "policy", "extension tags REJECTED_V1", "");
authoritativeCase("I1-P018", "policy", "duplicate fact policy DEDUP_IDENTICAL / REJECT_CONFLICTING", "");
authoritativeCase("I1-P020", "policy", "unstructured HTML extraction forbidden", "");
authoritativeCase("I1-P021", "policy", "nil facts rejected", "");
authoritativeCase("I1-P022", "policy", "segment/scenario dimensions rejected", "");
authoritativeCase("I1-P023", "policy", "iXBRL preferred structured source", "");
authoritativeCase("I1-P024", "policy", "taxonomy us-gaap/dei only", "");
authoritativeCase("I1-P025", "policy", "release retained with zero metrics", "");
authoritativeCase("I1-P026", "policy", "policy change creates new policy id", "");
authoritativeCase("I1-P027", "policy", "ingestion vs extraction policy distinct ids", "");
authoritativeCase("I1-P028", "policy", "CAS global scan forbidden in policy doctrine", "");
authoritativeCase("I1-P029", "policy", "unknown/forbidden field: observation with sourceItemCode → reject", "CANONICAL_UNKNOWN_FIELD");
authoritativeCase("I1-P030", "policy", "SEC_US_DOMESTIC_EARNINGS_RELEASE_ONLY_V1: datasetSeriesIdentity exact literal → accepted", "");
authoritativeCase("I1-P031", "policy", "OTHER: datasetSeriesIdentity different string → reject", "EARNINGS_DATASET_SERIES_IDENTITY_INVALID");
authoritativeCase("I1-P032", "policy", "admit + diagnostic: 8-K with items [2.01,2.02] + structured XBRL → ADMIT + EARNINGS_NON_EARNINGS_ITEM_PRESENT", "");
authoritativeCase("I1-P033", "policy", "reject: 8-K with 2.02 but opaque exhibit no structured → EARNINGS_STRUCTURED_DOCUMENT_ABSENT", "EARNINGS_STRUCTURED_DOCUMENT_ABSENT");
authoritativeCase("I1-P034", "policy", "admit empty: 8-K with 2.02 structured zero supported metrics → ADMIT + EARNINGS_NO_SUPPORTED_METRIC", "");
