import { authoritativeCase } from './helpers/earningsOfficialTestHarnessL4CIV1.mjs';

authoritativeCase("I1-C001", "contracts", "registry SNAPSHOT theoretical 129 after KEEP_NEW", "");
authoritativeCase("I1-C002", "contracts", "registry NORMALIZED length live", "");
authoritativeCase("I1-C003", "contracts", "KEEP_NEW schemaVersion list unique count 16", "");
authoritativeCase("I1-C004", "contracts", "EarningsIngestionPolicy/1 normalize roundtrip", "");
authoritativeCase("I1-C005", "contracts", "EarningsIngestionPolicy/1 unknown field", "");
authoritativeCase("I1-C006", "contracts", "EarningsIngestionPolicy/1 missing required", "");
authoritativeCase("I1-C007", "contracts", "EarningsMetricExtractionPolicy/1 normalize", "");
authoritativeCase("I1-C008", "contracts", "EarningsMetricExtractionPolicy/1 unknown field", "");
authoritativeCase("I1-C009", "contracts", "SecFilingSourceDocumentCore/1 normalize", "");
authoritativeCase("I1-C010", "contracts", "SecFilingSourceDocumentCore/1 unknown field", "");
authoritativeCase("I1-C011", "contracts", "SecFilingSourceDocumentCore/1 missing required", "");
authoritativeCase("I1-C012", "contracts", "SecDocumentBytesCore/1 normalize", "");
authoritativeCase("I1-C013", "contracts", "SecDocumentBytesCore/1 unknown field", "");
authoritativeCase("I1-C014", "contracts", "SecDocumentBytesCore/1 missing documentObjectId", "");
authoritativeCase("I1-C015", "contracts", "EarningsTaxonomyBundleManifest/1 normalize", "");
authoritativeCase("I1-C016", "contracts", "EarningsTaxonomyBundleManifest/1 unknown field", "");
authoritativeCase("I1-C017", "contracts", "XbrlCanonicalUnitCore/1 normalize USD", "");
authoritativeCase("I1-C018", "contracts", "XbrlCanonicalUnitCore/1 normalize USD_PER_SHARE", "");
authoritativeCase("I1-C019", "contracts", "XbrlCanonicalUnitCore/1 unknown field", "");
authoritativeCase("I1-C020", "contracts", "FinancialPeriodIdentityCore/1 normalize INSTANT", "");
authoritativeCase("I1-C021", "contracts", "FinancialPeriodIdentityCore/1 normalize DURATION", "");
authoritativeCase("I1-C022", "contracts", "FinancialPeriodIdentityCore/1 unknown field", "");
authoritativeCase("I1-C023", "contracts", "FinancialPeriodIdentityCore/1 missing dates", "");
authoritativeCase("I1-C024", "contracts", "EarningsEventIdentityCore/1 normalize minimal", "");
authoritativeCase("I1-C029", "contracts", "EarningsEventIdentityCore/1 unknown field", "");
authoritativeCase("I1-C030", "contracts", "EarningsEventIdentityCore/1 no sourceFilingDocumentId required", "");
authoritativeCase("I1-C031", "contracts", "EarningsRevisionIdentityCore/1 normalize", "");
authoritativeCase("I1-C032", "contracts", "EarningsRevisionIdentityCore/1 unknown field", "");
authoritativeCase("I1-C033", "contracts", "EarningsRevisionIdentityCore/1 rejects parent field", "");
authoritativeCase("I1-C034", "contracts", "EarningsRevisionCore/1 normalize INITIAL", "");
authoritativeCase("I1-C035", "contracts", "EarningsRevisionCore/1 unknown field", "");
authoritativeCase("I1-C036", "contracts", "EarningsMetricObservationCore/1 EPS normalize", "");
authoritativeCase("I1-C037", "contracts", "EarningsMetricObservationCore/1 Revenue normalize", "");
authoritativeCase("I1-C038", "contracts", "EarningsMetricObservationCore/1 unknown field", "");
authoritativeCase("I1-C039", "contracts", "EarningsMetricObservationCore/1 fixed-point minimal", "");
authoritativeCase("I1-C040", "contracts", "EarningsMetricObservationCore/1 fixed-point non-minimal", "");
authoritativeCase("I1-C041", "contracts", "EarningsMetricExtractionReport/1 normalize", "");
authoritativeCase("I1-C042", "contracts", "EarningsMetricExtractionReport/1 unknown field", "");
authoritativeCase("I1-C043", "contracts", "EarningsMetricExtractionReport/1 missing revision pin", "");
authoritativeCase("I1-C044", "contracts", "EarningsEventSetManifest/1 normalize", "");
authoritativeCase("I1-C045", "contracts", "EarningsEventSetManifest/1 unknown field", "");
authoritativeCase("I1-C046", "contracts", "EarningsEventSetManifest/1 count forge", "");
authoritativeCase("I1-C047", "contracts", "EarningsRevisionSetManifest/1 normalize 1 INITIAL/event", "");
authoritativeCase("I1-C048", "contracts", "EarningsRevisionSetManifest/1 unknown field", "");
authoritativeCase("I1-C049", "contracts", "EarningsRevisionSetManifest/1 digest forge", "");
authoritativeCase("I1-C050", "contracts", "Snapshot normalize with ExtractionSet+series+supersedes+digests", "");
authoritativeCase("I1-C051", "contracts", "EarningsDatasetSnapshotManifest/1 unknown field", "");
authoritativeCase("I1-C052", "contracts", "EarningsDatasetSnapshotManifest/1 missing required pin", "");
authoritativeCase("I1-C053", "contracts", "bad schemaVersion any contract", "");
authoritativeCase("I1-C054", "contracts", "TransformImplementationManifest/2 reuse normalize", "");
authoritativeCase("I1-C055", "contracts", "REJECT EarningsParserImplementationManifest/1 not registered", "");
authoritativeCase("I1-C056", "contracts", "closed field set no prototype pollution", "");
authoritativeCase("I1-C061", "contracts", "distinct ids: two FinancialPeriodIdentity payloads INSTANT vs DURATION → ids differ", "");
authoritativeCase("I1-C062", "contracts", "enum closed INSTANT|DURATION: periodType=YEAR_TO_DATE → reject", "EARNINGS_PERIOD_TYPE_INVALID");
authoritativeCase("I1-C063", "contracts", "enum closed: periodType=QUARTER → reject", "EARNINGS_PERIOD_TYPE_INVALID");
authoritativeCase("I1-C064", "contracts", "enum closed: periodType=FISCAL_YEAR → reject", "EARNINGS_PERIOD_TYPE_INVALID");
authoritativeCase("I1-C065", "contracts", "required field: Snapshot omit earningsExtractionSetManifestId → reject", "EARNINGS_SNAPSHOT_INVALID");
authoritativeCase("I1-C066", "contracts", "literal series required: Snapshot omit/wrong datasetSeriesIdentity → reject", "EARNINGS_DATASET_SERIES_IDENTITY_INVALID");
authoritativeCase("I1-C067", "contracts", "required digests: Snapshot omit orderedExtractionReportDigest or orderedMetricObservationDigest → reject", "EARNINGS_SNAPSHOT_INVALID");
authoritativeCase("I1-C068", "contracts", "nullable supersedes: Snapshot with supersedesEarningsDatasetSnapshotManifestId null root → accepted", "");
authoritativeCase("I1-C069", "contracts", "normalize: minimal valid EarningsExtractionSetManifest/1 → byte-stable id", "");
authoritativeCase("I1-C070", "contracts", "extra key: ExtractionSet unknown field → reject", "CANONICAL_UNKNOWN_FIELD");
authoritativeCase("I1-C071", "contracts", "omit revisionSetId: ExtractionSet missing required field → reject", "EARNINGS_EXTRACTION_SET_INVALID");
authoritativeCase("I1-C072", "contracts", "Foo/1: ExtractionSet bad schemaVersion → reject", "EARNINGS_EXTRACTION_SET_INVALID");
authoritativeCase("I1-C096", "contracts", "omit: Snapshot.orderedMetricObservationIdentityDigest required → reject", "EARNINGS_SNAPSHOT_INVALID");
authoritativeCase("I1-C097", "contracts", "bad type: Snapshot.extractionReportCount required non-neg int → reject", "EARNINGS_SNAPSHOT_INVALID");
