import { authoritativeCase } from './helpers/earningsOfficialTestHarnessL4CIV1.mjs';

authoritativeCase("I1-A001", "adversarial", "wire Symbol rejected", "");
authoritativeCase("I1-A002", "adversarial", "wire Date rejected", "");
authoritativeCase("I1-A003", "adversarial", "accession malformed", "");
authoritativeCase("I1-A004", "adversarial", "CIK mismatch accession", "");
authoritativeCase("I1-A005", "adversarial", "form 20-F rejected", "");
authoritativeCase("I1-A006", "adversarial", "form 40-F rejected", "");
authoritativeCase("I1-A007", "adversarial", "acceptanceDatetime wall clock", "");
authoritativeCase("I1-A008", "adversarial", "latest reference id", "");
authoritativeCase("I1-A009", "adversarial", "network during computation", "");
authoritativeCase("I1-A010", "adversarial", "path field forbidden", "");
authoritativeCase("I1-A011", "adversarial", "mtime field forbidden", "");
authoritativeCase("I1-A012", "adversarial", "machine field forbidden", "");
authoritativeCase("I1-A013", "adversarial", "EPS BASIC rejected", "");
authoritativeCase("I1-A014", "adversarial", "EPS NON_GAAP rejected", "");
authoritativeCase("I1-A015", "adversarial", "fixed-point NaN rejected", "");
authoritativeCase("I1-A016", "adversarial", "fixed-point -0 rejected", "");
authoritativeCase("I1-A017", "adversarial", "segment dimension rejected", "");
authoritativeCase("I1-A018", "adversarial", "extension tag rejected", "");
authoritativeCase("I1-A019", "adversarial", "fiscal classification attempt rejected (no YTD-as-quarter path)", "");
authoritativeCase("I1-A020", "adversarial", "derived period forbidden", "");
authoritativeCase("I1-A021", "adversarial", "orphan metric not in store", "");
authoritativeCase("I1-A022", "adversarial", "EventSet digest forge", "");
authoritativeCase("I1-A023", "adversarial", "ingestion-order dependent sort", "");
authoritativeCase("I1-A027", "adversarial", "closure completeness: missing ref inside snapshot closure → reject", "EARNINGS_CLOSURE_REFERENCE_MISSING");
authoritativeCase("I1-A028", "adversarial", "closure scope only: unexpected id in ExtractionSet closed lists; noise outside closure → reject unexpected; ignore outside", "EARNINGS_CLOSURE_UNEXPECTED_ID");
authoritativeCase("I1-A029", "adversarial", "forbidden: readdir/glob/latest tip discovery → reject", "EARNINGS_CAS_GLOBAL_SCAN_FORBIDDEN");
authoritativeCase("I1-A030", "adversarial", "unknown: EventSet + supersedes* unknown field → reject", "CANONICAL_UNKNOWN_FIELD");
authoritativeCase("I1-A031", "adversarial", "unknown: RevisionSet + supersedes* unknown field → reject", "CANONICAL_UNKNOWN_FIELD");
authoritativeCase("I1-A032", "adversarial", "unknown: ExtractionSet + supersedes* unknown field → reject", "CANONICAL_UNKNOWN_FIELD");
