import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseEnglishCivilDate, parseArchivedNasdaqTraderCalendar, reconcileAuthorities } from '../../../scripts/buildJarviseSessionCalendarXNYSHistorical.mjs';
import { normalizeMarketSessionCalendarCoreV2 } from '../src/contracts/marketCalendarL3V2.mjs';
const C=process.env.P1_CANDIDATE_ROOT;if(!C)throw new Error('P1_CANDIDATE_ROOT required');
const j=(p)=>JSON.parse(readFileSync(resolve(C,...p.split('/')),'utf8'));const y=(n,f)=>j(`data/jarvise/session-calendar-historical/XNYS/${n}/${f}`);const source=readFileSync(resolve(C,'scripts/buildJarviseSessionCalendarXNYSHistorical.mjs'),'utf8');
test('H1 EST and EDT offsets are derived',()=>{const s=y(2018,'session-calendar-core.json').sessions;assert.equal(s.find((x)=>x.sessionDate==='2018-01-02').openUtc,'2018-01-02T14:30:00.000Z');assert.equal(s.find((x)=>x.sessionDate==='2018-07-02').openUtc,'2018-07-02T13:30:00.000Z');});
test('H2 full holidays are excluded',()=>assert.ok(!y(2024,'session-calendar-core.json').sessions.some((x)=>x.sessionDate==='2024-07-04')));
test('H3 early closes end at 13 local',()=>assert.equal(y(2024,'session-calendar-core.json').sessions.find((x)=>x.sessionDate==='2024-11-29').closeUtc,'2024-11-29T18:00:00.000Z'));
test('H4 weekends are excluded',()=>assert.ok(y(2023,'session-calendar-core.json').sessions.every((x)=>!['2023-01-07','2023-01-08'].includes(x.sessionDate))));
test('H5 invalid civil date fails closed',()=>assert.throws(()=>parseEnglishCivilDate('February 30',2022)));
test('H6 duplicate Nasdaq date status fails closed',()=>{const h='<table><tr><th>Date</th><th>Holiday</th><th>Status</th></tr><tr><td>January 1, 2022</td><td>x</td><td>Closed</td></tr><tr><td>January 1, 2022</td><td>x</td><td>Closed</td></tr></table>';assert.throws(()=>parseArchivedNasdaqTraderCalendar(h,2022));});
test('H7 close not after open is rejected',()=>{const c=structuredClone(y(2019,'session-calendar-core.json'));c.sessions[0].closeUtc=c.sessions[0].openUtc;c.sessions[0].marketValidTime=c.sessions[0].closeUtc;assert.throws(()=>normalizeMarketSessionCalendarCoreV2(c));});
test('H8 marketValidTime must equal closeUtc',()=>{const c=structuredClone(y(2019,'session-calendar-core.json'));c.sessions[0].marketValidTime=c.sessions[0].openUtc;assert.throws(()=>normalizeMarketSessionCalendarCoreV2(c));});
test('H9 fixture namespace is V2',()=>assert.equal(y(2020,'normalized-source.json').calendarNamespaceVersion,'WHEEL_JARVISE_US_EQUITY_XNYS_CALENDAR/2'));
test('H10 all emitted references are sha256 CAS ids',()=>{for(const n of [2018,2026])for(const id of [y(n,'PROVENANCE.json').calendarAuthorityPolicyId,y(n,'PROVENANCE.json').timeZoneRulesetId,y(n,'PROVENANCE.json').calendarCoreId])assert.match(id,/^sha256:[0-9a-f]{64}$/);});
test('H11 authority disagreement fails before overlay',()=>assert.throws(()=>reconcileAuthorities({fullClosureDates:['2020-01-01'],earlyCloseDates:[]},{fullClosureDates:[],earlyCloseDates:[]},2020),/US_EQUITY_CALENDAR_AUTHORITY_CONFLICT/));
test('H12 sweep result vocabulary is closed',()=>{for(const n of [2018,2022,2025])assert.ok(['INSUFFICIENT','EXTRA_ROWS_IDENTIFIED','NO_EXTRA_ROWS_IN_BOUND_SOURCES'].includes(j(`data/jarvise/session-calendar-historical/source-evidence/${n}/EXCEPTIONAL_CLOSURE_SWEEP.json`).result));});
test('H13 R0001 has no superseded registry',()=>assert.equal(j('data/jarvise/session-calendar-historical/XNYS/registry/R0001/registry-manifest.json').supersedesCalendarRegistryManifestId,null));
test('H14 UTC session instants use derivation primitive',()=>{assert.match(source,/deriveNewYorkUtcInstantV1\(d,'09:30'\)/);assert.doesNotMatch(source,/T14:30:00\.000Z.*session/);});
test('H15 builder has no wall clock dependency',()=>{assert.doesNotMatch(source,/Date\.now\(|new Date\(/);});
test('H16 timezone bounds are complete and contiguous',()=>{const r=y(2020,'timezone-ruleset.json');assert.equal(r.civilDateBounds.length,366);for(let i=1;i<r.civilDateBounds.length;i++)assert.equal(r.civilDateBounds[i-1].endUtcExclusive,r.civilDateBounds[i].startUtc);});
test('H17 sessions are unique sorted and valid',()=>{for(const n of [2018,2022,2026]){const s=y(n,'session-calendar-core.json').sessions,d=s.map((x)=>x.sessionDate);assert.deepEqual(d,[...d].sort());assert.equal(new Set(d).size,d.length);}});
test('H18 no historical 2026 evidence output exists',()=>assert.throws(()=>readFileSync(resolve(C,'data/jarvise/session-calendar-historical/source-evidence/2026/SOURCE_DIGESTS.json'))));
