import { authoritativeCase } from './helpers/earningsOfficialTestHarnessL4CIV1.mjs';

authoritativeCase("I1-G001", "revision-set", "RevisionSet valid iff each event orderedRevisions.length===1 INITIAL parent=null", "");
authoritativeCase("I1-G002", "revision-set", "RevisionSet entry pins revisionCore + revisionIdentity", "");
authoritativeCase("I1-G003", "revision-set", "orderedEventChains order canonical by event id", "");
authoritativeCase("I1-G004", "revision-set", "revisionCount === eventCount always in V1", "");
authoritativeCase("I1-G005", "revision-set", "orderedRevisionIdentityDigest recomputed", "");
authoritativeCase("I1-G007", "revision-set", "branch rejected (and any second revision rejected first)", "");
authoritativeCase("I1-G008", "revision-set", "foreign parent rejected (parent must be null anyway)", "");
authoritativeCase("I1-G009", "revision-set", "missing parent rejected; V1 requires parent=null so non-null missing still reject", "");
authoritativeCase("I1-G010", "revision-set", "cycle rejected", "");
authoritativeCase("I1-G011", "revision-set", "self-parent rejected", "");
authoritativeCase("I1-G014", "revision-set", "zero revisions for an event rejected", "");
authoritativeCase("I1-G015", "revision-set", "INITIAL with null parent accepted", "");
authoritativeCase("I1-G016", "revision-set", "entry.revisionIdentityId === core.earningsRevisionIdentityId", "");
authoritativeCase("I1-G019", "revision-set", "EventSet rejects unknown supersedes* field", "");
authoritativeCase("I1-G020", "revision-set", "duplicate revision identity in set", "");
authoritativeCase("I1-G021", "revision-set", "RevisionSet unknown field", "");
authoritativeCase("I1-G022", "revision-set", "forest of independent events each with INITIAL", "");
authoritativeCase("I1-G023", "revision-set", "RevisionCore kind INITIAL required for root", "");
authoritativeCase("I1-G025", "revision-set", "V1 single INITIAL null parent: orderedRevisions.length===2 or parent!=null → reject", "EARNINGS_REVISION_COUNT_PER_EVENT_INVALID");
authoritativeCase("I1-G026", "revision-set", "tip === that revision: single INITIAL event → tip id equal", "");
authoritativeCase("I1-G027", "revision-set", "unknown field: RevisionSet + supersedesRevisionSetManifestId → reject", "CANONICAL_UNKNOWN_FIELD");
authoritativeCase("I1-G028", "revision-set", "immutability / count: second version same accession → reject", "EARNINGS_REVISION_COUNT_PER_EVENT_INVALID");
authoritativeCase("I1-G029", "revision-set", "invalid V1: chain length>1 → reject", "EARNINGS_REVISION_COUNT_PER_EVENT_INVALID");
authoritativeCase("I1-G030", "revision-set", "new CAS id; no supersedes field: RevisionSet content change → new id; old retained", "");
authoritativeCase("I1-G031", "revision-set", "1 rev: event with exactly one INITIAL parent=null → accepted", "");
authoritativeCase("I1-G032", "revision-set", "[]: event with zero revisions → reject", "EARNINGS_REVISION_COUNT_PER_EVENT_INVALID");
authoritativeCase("I1-G033", "revision-set", "parent set: parentRevisionIdentityId non-null → reject", "EARNINGS_REVISION_PARENT_FORBIDDEN_V1");
authoritativeCase("I1-G034", "revision-set", "REPUB: revisionKind other than INITIAL → reject", "EARNINGS_REVISION_KIND_FORBIDDEN_V1");
authoritativeCase("I1-G035", "revision-set", "/A: 8-K/A new accession independent event+INITIAL → accepted independent", "");
