import { authoritativeCase } from './helpers/earningsOfficialTestHarnessL4CIV1.mjs';

authoritativeCase("I1-H019", "snapshot", "root: root snapshot previousSnapshotId=null → supersedes=null; created:true", "");
authoritativeCase("I1-H020", "snapshot", "parent id: parent snapshot valid same datasetIdentityKey → accepted supersedes", "");
authoritativeCase("I1-H021", "snapshot", "same functional: identical functional fingerprint → previousSnapshotId; created:false", "");
authoritativeCase("I1-H022", "snapshot", "change count/digest: functional field change → new snapshot; supersedes=previous", "");
authoritativeCase("I1-H023", "snapshot", "missing parent: previousSnapshotId absent from CAS → reject", "EARNINGS_SNAPSHOT_PARENT_MISSING");
authoritativeCase("I1-H024", "snapshot", "foreign series: parent different datasetSeriesIdentity → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_FOREIGN_DATASET");
authoritativeCase("I1-H025", "snapshot", "foreign jur: parent different jurisdictionCode → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_FOREIGN_DATASET");
authoritativeCase("I1-H026", "snapshot", "foreign cur: parent different currencyCode → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_FOREIGN_DATASET");
authoritativeCase("I1-H027", "snapshot", "foreign auth: parent different allowedSourceAuthority → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_FOREIGN_DATASET");
authoritativeCase("I1-H028", "snapshot", "self id: supersedes == self → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_CYCLE");
authoritativeCase("I1-H029", "snapshot", "2-cycle: A supersedes B and B supersedes A → reject", "EARNINGS_SNAPSHOT_SUPERSESSION_CYCLE");
authoritativeCase("I1-H030", "snapshot", "reread parent: after new snapshot, parent bytes unchanged → byte-identical", "");
authoritativeCase("I1-H031", "snapshot", "mismatch: Snapshot.series != IngestionPolicy.series → reject", "EARNINGS_DATASET_SERIES_IDENTITY_MISMATCH");
authoritativeCase("I1-H032", "snapshot", "series A vs B: datasetIdentityKey changes when series changes → keys differ", "");
authoritativeCase("I1-H033", "snapshot", "P1/P2: parser TIM/2 different; same series → compatible series; new snapshot", "");
authoritativeCase("I1-H034", "snapshot", "tax A/B: taxonomy different; same series → compatible; new snapshot", "");
authoritativeCase("I1-H035", "snapshot", "pol A/B: extraction policy different; same series → compatible; new snapshot", "");
authoritativeCase("I1-H036", "snapshot", "mismatch: Report.transform != Snapshot.transform → reject", "EARNINGS_TRANSFORM_IMPLEMENTATION_ID_MISMATCH");
authoritativeCase("I1-H037", "snapshot", "mismatch: ExtractionSet.transform != Snapshot.transform → reject", "EARNINGS_TRANSFORM_IMPLEMENTATION_ID_MISMATCH");
authoritativeCase("I1-H038", "snapshot", "mismatch: Report.policy != Snapshot.policy → reject", "EARNINGS_EXTRACTION_POLICY_ID_MISMATCH");
authoritativeCase("I1-H039", "snapshot", "mismatch: ExtractionSet.policy != Snapshot.policy → reject", "EARNINGS_EXTRACTION_POLICY_ID_MISMATCH");
authoritativeCase("I1-H040", "snapshot", "mismatch: Report.taxonomy != Snapshot.taxonomy → reject", "EARNINGS_TAXONOMY_BUNDLE_ID_MISMATCH");
authoritativeCase("I1-H041", "snapshot", "mismatch: ExtractionSet.taxonomy != Snapshot.taxonomy → reject", "EARNINGS_TAXONOMY_BUNDLE_ID_MISMATCH");
authoritativeCase("I1-H042", "snapshot", "mismatch: ExtractionSet.revisionSet != Snapshot.revisionSet → reject", "EARNINGS_REVISION_SET_ID_MISMATCH");
authoritativeCase("I1-H043", "snapshot", "all equal: all technical ids equal across Snapshot/EXS/Report → accepted", "");
authoritativeCase("I1-H044", "snapshot", "fixture fields: golden functionalSnapshotFingerprint preimage → digest match", "");
authoritativeCase("I1-H045", "snapshot", "flip count: change one functional field → fingerprint changes", "");
authoritativeCase("I1-H046", "snapshot", "supersedes different: change supersedes only → fingerprint identical", "");
authoritativeCase("I1-H047", "snapshot", "cross platform: Windows vs Linux scalar encoding → same fingerprint", "");
authoritativeCase("I1-H048", "snapshot", "null bound: null scalar encoding → encodes as null", "");
authoritativeCase("I1-H049", "snapshot", "emptySnapshot: bool scalar encoding → true/false", "");
authoritativeCase("I1-H050", "snapshot", "counts: integer canonical decimal → no leading zeros", "");
authoritativeCase("I1-H051", "snapshot", "instant: timestamp UTC normalized → UTC form", "");
authoritativeCase("I1-H052", "snapshot", "uppercase attempt: ID lowercase sha256 → canonical lowercase", "");
authoritativeCase("I1-H053", "snapshot", "permute admit order: ingestion order permutation → fingerprint identical", "");
authoritativeCase("I1-R015", "snapshot", "no-op: re-ingest identical functional dataset with previousSnapshotId → same id; created:false", "");
authoritativeCase("I1-R016", "snapshot", "snapshot supersedes only: functional change with previousSnapshotId → new snapshot; supersedes=previous; children CAS-pure", "");
