import assert from 'node:assert/strict';
import { fixtureInput, createOutcomeDatasetSnapshot } from '../fixtures/label-consumer-fixture.mjs';
import { buildLabelOutcome } from '../implementation/label-engine-v1.mjs';
import { authorizeConsumption } from '../implementation/consumption-boundary-v1.mjs';
const clone = (v) => ({ ...v, observation: { ...v.observation }, horizon: { ...v.horizon }, calendarSessions: v.calendarSessions.map((session) => ({ ...session })), windowBars: v.windowBars.map((bar) => ({ ...bar })), labels: [...v.labels] });
let input = clone(fixtureInput); input.observation.AvailableAt = '2026-01-03T00:00:00Z'; assert.equal(buildLabelOutcome(input).status, 'BLOCKED');
input = clone(fixtureInput); input.horizon.sessionCount = 365; assert.throws(() => buildLabelOutcome(input));
input = clone(fixtureInput); input.windowBars[1].priceBasisId = 'DERIVED_ADJUSTED'; assert.equal(buildLabelOutcome(input).status, 'FAIL_CLOSED');
input = clone(fixtureInput); input.now = '2026-02-01T00:00:00Z'; assert.equal(buildLabelOutcome(input).status, 'NOT_YET_RESOLVED');
assert.equal(authorizeConsumption({ gateId: 'GATE23', features: ['laggedOutcome'] }).status, 'BLOCKED');
input = clone(fixtureInput); input.windowBars.pop(); assert.equal(buildLabelOutcome(input).status, 'INSUFFICIENT_DATA'); assert.equal(buildLabelOutcome(input).outcomeId, undefined);
input = clone(fixtureInput); input.windowBars[1].sessionDate = input.windowBars[0].sessionDate; assert.equal(buildLabelOutcome(input).status, 'INSUFFICIENT_DATA');
input = clone(fixtureInput); input.windowBars[1].sessionDate = '2026-04-01'; assert.equal(buildLabelOutcome(input).status, 'INSUFFICIENT_DATA');
input = clone(fixtureInput); delete input.windowBars[0].settlingAt; assert.equal(buildLabelOutcome(input).status, 'INSUFFICIENT_DATA');
input = clone(fixtureInput); input.outcomeDatasetId = 'arbitrary-dataset-id'; assert.throws(() => buildLabelOutcome(input), /OUTCOME_DATASET_ID_MISMATCH/);
input = clone(fixtureInput); input.outcomeDatasetId = input.outcomeDatasetSnapshot.snapshotDatasetManifestId; assert.equal(buildLabelOutcome(input).status, 'RESOLVED');
const providerB = createOutcomeDatasetSnapshot({ providerId: 'fixture-provider-b' });
input = clone(fixtureInput); input.outcomeDatasetSnapshot = providerB; const alternate = buildLabelOutcome(input);
assert.notEqual(input.outcomeDatasetSnapshot.snapshotDatasetManifestId, fixtureInput.outcomeDatasetSnapshot.snapshotDatasetManifestId); assert.notEqual(alternate.outcomeId, buildLabelOutcome(fixtureInput).outcomeId);
console.log('GATE22_HOSTILES_PASS 15');
